"""empty message

Revision ID: d14c484ca700
Revises: 5ac5632a059e
Create Date: 2021-07-26 09:58:37.050405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14c484ca700'
down_revision = '5ac5632a059e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_created')
    # ### end Alembic commands ###
